// Re-downloads the bundled webfaces from Google Fonts and rewrites
// packages/ui/src/styles/fonts.css. The fonts are committed, so this only
// needs running to add a weight or refresh a version.
//
//   node scripts/fetch-fonts.mjs
//
// Only latin and latin-ext are kept: the UI is English and the mono face
// carries code and identifiers. Both families are OFL 1.1 (see fonts/OFL.txt).
import { writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const STYLES = join(dirname(fileURLToPath(import.meta.url)), '..', 'packages', 'ui', 'src', 'styles');
const API = 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap';
// Google serves woff2 only to browsers that advertise support.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const SUBSETS = { 'U+0000-00FF': 'latin', 'U+0100-02BA': 'latin-ext' };

const css = execFileSync('curl', ['-sS', '-A', UA, API], { encoding: 'utf8' });
mkdirSync(join(STYLES, 'fonts'), { recursive: true });

const faces = [];
for (const block of css.split('@font-face').slice(1)) {
  const family = block.match(/font-family: '([^']+)'/)[1];
  const weight = block.match(/font-weight: (\d+)/)[1];
  const url = block.match(/src: url\(([^)]+)\)/)[1];
  const range = block.match(/unicode-range: ([^;]+);/)[1].trim();
  const subset = Object.entries(SUBSETS).find(([prefix]) => range.startsWith(prefix))?.[1];
  if (!subset) continue;
  const file = `fonts/${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`;
  execFileSync('curl', ['-sS', '-o', join(STYLES, file), url]);
  faces.push({ family, weight, file, range });
}

const header = `/* Bundled webfonts. Cyberloom ships these rather than fetching them, so the
 * shell renders correctly with no network at all (SPEC 15.13: offline is a
 * supported state). Both families are SIL Open Font License 1.1 - see
 * fonts/OFL.txt. Only the latin and latin-ext subsets are bundled; the app's
 * UI is English and the mono face is used for code and identifiers.
 *
 * Generated by scripts/fetch-fonts.mjs - do not edit by hand.
 */`;

writeFileSync(
  join(STYLES, 'fonts.css'),
  header + '\n\n' + faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./${f.file}') format('woff2');
  unicode-range: ${f.range};
}`).join('\n\n') + '\n',
);
console.log(`wrote fonts.css and ${faces.length} font files`);
