// Generates packages/ui/src/components/icons.ts from the design folder's icon
// table, so the application renders exactly the glyphs the artboards do.
//
//   node scripts/gen-icons.mjs
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICONS } from '../design/cyberloom/icons.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const names = Object.keys(ICONS).sort();

const out = `// Generated by scripts/gen-icons.mjs from design/cyberloom/icons.mjs.
// Do not edit by hand: edit the design table and regenerate, so the mockups
// and the application never show different glyphs.
//
// Each value is the inner markup of a 24x24 SVG drawn with no fill and a
// round-capped stroke. <Icon> supplies size, colour and stroke width.

export const ICONS = {
${names.map((n) => `  ${n}: ${JSON.stringify(ICONS[n])},`).join('\n')}
} as const;

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as IconName[];
`;

writeFileSync(join(root, 'packages/ui/src/components/icons.ts'), out);
console.log(`wrote ${names.length} icons`);
